// Generated by scripts/add-storage-layout.ts — do not edit by hand.
import type { LayoutEntry } from '../storageLayoutTypes';

export const AaveOracle: LayoutEntry = {
  source:
    '../../lib/aave-address-book/lib/aave-v3-origin src/contracts/misc/AaveOracle.sol:AaveOracle',
  layout: {
    storage: [
      {
        astId: 601,
        contract: 'src/contracts/misc/AaveOracle.sol:AaveOracle',
        label: 'assetsSources',
        offset: 0,
        slot: '0',
        type: 't_mapping(t_address,t_contract(AggregatorInterface)90)',
      },
      {
        astId: 604,
        contract: 'src/contracts/misc/AaveOracle.sol:AaveOracle',
        label: '_fallbackOracle',
        offset: 0,
        slot: '1',
        type: 't_contract(IPriceOracleGetter)576',
      },
    ],
    types: {
      t_address: { encoding: 'inplace', label: 'address', numberOfBytes: '20' },
      't_contract(AggregatorInterface)90': {
        encoding: 'inplace',
        label: 'contract AggregatorInterface',
        numberOfBytes: '20',
      },
      't_contract(IPriceOracleGetter)576': {
        encoding: 'inplace',
        label: 'contract IPriceOracleGetter',
        numberOfBytes: '20',
      },
      't_mapping(t_address,t_contract(AggregatorInterface)90)': {
        encoding: 'mapping',
        key: 't_address',
        label: 'mapping(address => contract AggregatorInterface)',
        numberOfBytes: '32',
        value: 't_contract(AggregatorInterface)90',
      },
    },
  },
};
