// Generated by scripts/add-storage-layout.ts — do not edit by hand.
import type { LayoutEntry } from '../storageLayoutTypes';

export const ACLManager: LayoutEntry = {
  source:
    '../../lib/aave-address-book/lib/aave-v3-origin src/contracts/protocol/configuration/ACLManager.sol:ACLManager',
  layout: {
    storage: [
      {
        astId: 24,
        contract: 'src/contracts/protocol/configuration/ACLManager.sol:ACLManager',
        label: '_roles',
        offset: 0,
        slot: '0',
        type: 't_mapping(t_bytes32,t_struct(RoleData)19_storage)',
      },
    ],
    types: {
      t_address: { encoding: 'inplace', label: 'address', numberOfBytes: '20' },
      t_bool: { encoding: 'inplace', label: 'bool', numberOfBytes: '1' },
      t_bytes32: { encoding: 'inplace', label: 'bytes32', numberOfBytes: '32' },
      't_mapping(t_address,t_bool)': {
        encoding: 'mapping',
        key: 't_address',
        label: 'mapping(address => bool)',
        numberOfBytes: '32',
        value: 't_bool',
      },
      't_mapping(t_bytes32,t_struct(RoleData)19_storage)': {
        encoding: 'mapping',
        key: 't_bytes32',
        label: 'mapping(bytes32 => struct AccessControl.RoleData)',
        numberOfBytes: '32',
        value: 't_struct(RoleData)19_storage',
      },
      't_struct(RoleData)19_storage': {
        encoding: 'inplace',
        label: 'struct AccessControl.RoleData',
        numberOfBytes: '64',
        members: [
          {
            astId: 16,
            contract: 'src/contracts/protocol/configuration/ACLManager.sol:ACLManager',
            label: 'members',
            offset: 0,
            slot: '0',
            type: 't_mapping(t_address,t_bool)',
          },
          {
            astId: 18,
            contract: 'src/contracts/protocol/configuration/ACLManager.sol:ACLManager',
            label: 'adminRole',
            offset: 0,
            slot: '1',
            type: 't_bytes32',
          },
        ],
      },
    },
  },
};
