// Generated by scripts/add-storage-layout.ts — do not edit by hand.
import type { LayoutEntry } from '../storageLayoutTypes';

export const PermissionedPayloadsController: LayoutEntry = {
  source:
    'aave-dao/aave-governance-v3@497226e src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
  layout: {
    storage: [
      {
        astId: 8,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_owner',
        offset: 0,
        slot: '0',
        type: 't_address',
      },
      {
        astId: 3544,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_guardian',
        offset: 0,
        slot: '1',
        type: 't_address',
      },
      {
        astId: 3380,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_initialized',
        offset: 20,
        slot: '1',
        type: 't_uint8',
      },
      {
        astId: 3383,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_initializing',
        offset: 21,
        slot: '1',
        type: 't_bool',
      },
      {
        astId: 4035,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_payloadsCount',
        offset: 22,
        slot: '1',
        type: 't_uint40',
      },
      {
        astId: 4041,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_accessLevelToExecutorConfig',
        offset: 0,
        slot: '2',
        type: 't_mapping(t_enum(AccessControl)4879,t_struct(ExecutorConfig)5224_storage)',
      },
      {
        astId: 4046,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_payloads',
        offset: 0,
        slot: '3',
        type: 't_mapping(t_uint40,t_struct(Payload)5275_storage)',
      },
      {
        astId: 5083,
        contract:
          'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
        label: '_payloadsManager',
        offset: 0,
        slot: '4',
        type: 't_address',
      },
    ],
    types: {
      t_address: { encoding: 'inplace', label: 'address', numberOfBytes: '20' },
      't_array(t_struct(ExecutionAction)5247_storage)dyn_storage': {
        encoding: 'dynamic_array',
        label: 'struct IPayloadsControllerCore.ExecutionAction[]',
        numberOfBytes: '32',
        base: 't_struct(ExecutionAction)5247_storage',
      },
      t_bool: { encoding: 'inplace', label: 'bool', numberOfBytes: '1' },
      t_bytes_storage: { encoding: 'bytes', label: 'bytes', numberOfBytes: '32' },
      't_enum(AccessControl)4879': {
        encoding: 'inplace',
        label: 'enum PayloadsControllerUtils.AccessControl',
        numberOfBytes: '1',
      },
      't_enum(PayloadState)5218': {
        encoding: 'inplace',
        label: 'enum IPayloadsControllerCore.PayloadState',
        numberOfBytes: '1',
      },
      't_mapping(t_enum(AccessControl)4879,t_struct(ExecutorConfig)5224_storage)': {
        encoding: 'mapping',
        key: 't_enum(AccessControl)4879',
        label:
          'mapping(enum PayloadsControllerUtils.AccessControl => struct IPayloadsControllerCore.ExecutorConfig)',
        numberOfBytes: '32',
        value: 't_struct(ExecutorConfig)5224_storage',
      },
      't_mapping(t_uint40,t_struct(Payload)5275_storage)': {
        encoding: 'mapping',
        key: 't_uint40',
        label: 'mapping(uint40 => struct IPayloadsControllerCore.Payload)',
        numberOfBytes: '32',
        value: 't_struct(Payload)5275_storage',
      },
      t_string_storage: { encoding: 'bytes', label: 'string', numberOfBytes: '32' },
      't_struct(ExecutionAction)5247_storage': {
        encoding: 'inplace',
        label: 'struct IPayloadsControllerCore.ExecutionAction',
        numberOfBytes: '128',
        members: [
          {
            astId: 5235,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'target',
            offset: 0,
            slot: '0',
            type: 't_address',
          },
          {
            astId: 5237,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'withDelegateCall',
            offset: 20,
            slot: '0',
            type: 't_bool',
          },
          {
            astId: 5240,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'accessLevel',
            offset: 21,
            slot: '0',
            type: 't_enum(AccessControl)4879',
          },
          {
            astId: 5242,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'value',
            offset: 0,
            slot: '1',
            type: 't_uint256',
          },
          {
            astId: 5244,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'signature',
            offset: 0,
            slot: '2',
            type: 't_string_storage',
          },
          {
            astId: 5246,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'callData',
            offset: 0,
            slot: '3',
            type: 't_bytes_storage',
          },
        ],
      },
      't_struct(ExecutorConfig)5224_storage': {
        encoding: 'inplace',
        label: 'struct IPayloadsControllerCore.ExecutorConfig',
        numberOfBytes: '32',
        members: [
          {
            astId: 5221,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'executor',
            offset: 0,
            slot: '0',
            type: 't_address',
          },
          {
            astId: 5223,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'delay',
            offset: 20,
            slot: '0',
            type: 't_uint40',
          },
        ],
      },
      't_struct(Payload)5275_storage': {
        encoding: 'inplace',
        label: 'struct IPayloadsControllerCore.Payload',
        numberOfBytes: '96',
        members: [
          {
            astId: 5250,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'creator',
            offset: 0,
            slot: '0',
            type: 't_address',
          },
          {
            astId: 5253,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'maximumAccessLevelRequired',
            offset: 20,
            slot: '0',
            type: 't_enum(AccessControl)4879',
          },
          {
            astId: 5256,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'state',
            offset: 21,
            slot: '0',
            type: 't_enum(PayloadState)5218',
          },
          {
            astId: 5258,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'createdAt',
            offset: 22,
            slot: '0',
            type: 't_uint40',
          },
          {
            astId: 5260,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'queuedAt',
            offset: 27,
            slot: '0',
            type: 't_uint40',
          },
          {
            astId: 5262,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'executedAt',
            offset: 0,
            slot: '1',
            type: 't_uint40',
          },
          {
            astId: 5264,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'cancelledAt',
            offset: 5,
            slot: '1',
            type: 't_uint40',
          },
          {
            astId: 5266,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'expirationTime',
            offset: 10,
            slot: '1',
            type: 't_uint40',
          },
          {
            astId: 5268,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'delay',
            offset: 15,
            slot: '1',
            type: 't_uint40',
          },
          {
            astId: 5270,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'gracePeriod',
            offset: 20,
            slot: '1',
            type: 't_uint40',
          },
          {
            astId: 5274,
            contract:
              'src/contracts/payloads/PermissionedPayloadsController.sol:PermissionedPayloadsController',
            label: 'actions',
            offset: 0,
            slot: '2',
            type: 't_array(t_struct(ExecutionAction)5247_storage)dyn_storage',
          },
        ],
      },
      t_uint256: { encoding: 'inplace', label: 'uint256', numberOfBytes: '32' },
      t_uint40: { encoding: 'inplace', label: 'uint40', numberOfBytes: '5' },
      t_uint8: { encoding: 'inplace', label: 'uint8', numberOfBytes: '1' },
    },
  },
};
