// Generated by scripts/add-storage-layout.ts — do not edit by hand.
import type { LayoutEntry } from '../storageLayoutTypes';

export const PoolConfiguratorInstance: LayoutEntry = {
  source:
    '../../lib/aave-address-book/lib/aave-v3-origin src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
  layout: {
    storage: [
      {
        astId: 2890,
        contract: 'src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
        label: 'lastInitializedRevision',
        offset: 0,
        slot: '0',
        type: 't_uint256',
      },
      {
        astId: 2893,
        contract: 'src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
        label: 'initializing',
        offset: 0,
        slot: '1',
        type: 't_bool',
      },
      {
        astId: 2963,
        contract: 'src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
        label: '______gap',
        offset: 0,
        slot: '2',
        type: 't_array(t_uint256)50_storage',
      },
      {
        astId: 5126,
        contract: 'src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
        label: '_addressesProvider',
        offset: 0,
        slot: '52',
        type: 't_contract(IPoolAddressesProvider)2001',
      },
      {
        astId: 5129,
        contract: 'src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
        label: '_pool',
        offset: 0,
        slot: '53',
        type: 't_contract(IPool)1792',
      },
      {
        astId: 5133,
        contract: 'src/contracts/instances/PoolConfiguratorInstance.sol:PoolConfiguratorInstance',
        label: '_pendingLtv',
        offset: 0,
        slot: '54',
        type: 't_mapping(t_address,t_uint256)',
      },
    ],
    types: {
      t_address: { encoding: 'inplace', label: 'address', numberOfBytes: '20' },
      't_array(t_uint256)50_storage': {
        encoding: 'inplace',
        label: 'uint256[50]',
        numberOfBytes: '1600',
        base: 't_uint256',
      },
      t_bool: { encoding: 'inplace', label: 'bool', numberOfBytes: '1' },
      't_contract(IPool)1792': {
        encoding: 'inplace',
        label: 'contract IPool',
        numberOfBytes: '20',
      },
      't_contract(IPoolAddressesProvider)2001': {
        encoding: 'inplace',
        label: 'contract IPoolAddressesProvider',
        numberOfBytes: '20',
      },
      't_mapping(t_address,t_uint256)': {
        encoding: 'mapping',
        key: 't_address',
        label: 'mapping(address => uint256)',
        numberOfBytes: '32',
        value: 't_uint256',
      },
      t_uint256: { encoding: 'inplace', label: 'uint256', numberOfBytes: '32' },
    },
  },
};
