// Generated by scripts/add-storage-layout.ts — do not edit by hand.
import type { LayoutEntry } from '../storageLayoutTypes';

export const PoolAddressesProvider: LayoutEntry = {
  source:
    '../../lib/aave-address-book/lib/aave-v3-origin src/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider',
  layout: {
    storage: [
      {
        astId: 330,
        contract:
          'src/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider',
        label: '_owner',
        offset: 0,
        slot: '0',
        type: 't_address',
      },
      {
        astId: 988,
        contract:
          'src/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider',
        label: '_marketId',
        offset: 0,
        slot: '1',
        type: 't_string_storage',
      },
      {
        astId: 992,
        contract:
          'src/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider',
        label: '_addresses',
        offset: 0,
        slot: '2',
        type: 't_mapping(t_bytes32,t_address)',
      },
    ],
    types: {
      t_address: { encoding: 'inplace', label: 'address', numberOfBytes: '20' },
      t_bytes32: { encoding: 'inplace', label: 'bytes32', numberOfBytes: '32' },
      't_mapping(t_bytes32,t_address)': {
        encoding: 'mapping',
        key: 't_bytes32',
        label: 'mapping(bytes32 => address)',
        numberOfBytes: '32',
        value: 't_address',
      },
      t_string_storage: { encoding: 'bytes', label: 'string', numberOfBytes: '32' },
    },
  },
};
